### ISSUE TITLE
implement queue

### ISSUE THREAD

**Issue by jennifertchou** [johnlee1/hana-wiki#5]

**Comment by johnlee1** [comment]
So before we decided that when a post is made on a page, we would update the queues of all the users who are following that page. 

Instead I think we should dynamically obtain the data needed for a queue when a queue is requested.

So to do this we need to update the user model to have a queue. The queue could just be a list of all the posts on the queue

Then we need an api endpoint like this.
{
    method: 'GET',
    path: '/api/users/me/queue',
    config: Users.queue,
}

The Users.queue method should go through all the pages and get all the posts on the pages and return a list of the posts.
